language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

bioc_packages:
  - ggtree

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - Giappo/mbd
  - richelbilderbeek/becosys
  - richelbilderbeek/pirouette@richel

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  - Rscript -e 'devtools::install_github("Giappo/mbd")'

script:
  - travis_wait 50 R CMD build .
  - travis_wait 50 R CMD check *tar.gz
  # Check dead links
  - # rm .travis.yml
  - # ./scripts/check_dead_links

after_success:
  - Rscript -e 'covr::codecov()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"

after_fail:
  - cat /home/travis/build/richelbilderbeek/razzo/razzo.Rcheck/00check.log
