language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

bioc_packages:
  - ggtree

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - Giappo/mbd
  - richelbilderbeek/becosys
  - richelbilderbeek/pirouette@richel

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e 'mauricer::install_beast2_pkg("NS")'
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  - Rscript -e 'devtools::install_github("Giappo/mbd")'

script:
  - travis_wait 50 R CMD build .
  - travis_wait 50 R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
